// Code generated by mockery v2.44.1. DO NOT EDIT.

package hftorderbook

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// mockOrderbookDistributed is an autogenerated mock type for the orderbookDistributed type
type mockOrderbookDistributed struct {
	mock.Mock
}

type mockOrderbookDistributed_Expecter struct {
	mock *mock.Mock
}

func (_m *mockOrderbookDistributed) EXPECT() *mockOrderbookDistributed_Expecter {
	return &mockOrderbookDistributed_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: _a0, _a1, _a2
func (_m *mockOrderbookDistributed) Add(_a0 context.Context, _a1 float64, _a2 *Order) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, float64, *Order) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockOrderbookDistributed_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type mockOrderbookDistributed_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 float64
//   - _a2 *Order
func (_e *mockOrderbookDistributed_Expecter) Add(_a0 interface{}, _a1 interface{}, _a2 interface{}) *mockOrderbookDistributed_Add_Call {
	return &mockOrderbookDistributed_Add_Call{Call: _e.mock.On("Add", _a0, _a1, _a2)}
}

func (_c *mockOrderbookDistributed_Add_Call) Run(run func(_a0 context.Context, _a1 float64, _a2 *Order)) *mockOrderbookDistributed_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(float64), args[2].(*Order))
	})
	return _c
}

func (_c *mockOrderbookDistributed_Add_Call) Return(_a0 error) *mockOrderbookDistributed_Add_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockOrderbookDistributed_Add_Call) RunAndReturn(run func(context.Context, float64, *Order) error) *mockOrderbookDistributed_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Cancel provides a mock function with given fields: _a0, _a1, _a2
func (_m *mockOrderbookDistributed) Cancel(_a0 context.Context, _a1 float64, _a2 *Order) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Cancel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, float64, *Order) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockOrderbookDistributed_Cancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cancel'
type mockOrderbookDistributed_Cancel_Call struct {
	*mock.Call
}

// Cancel is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 float64
//   - _a2 *Order
func (_e *mockOrderbookDistributed_Expecter) Cancel(_a0 interface{}, _a1 interface{}, _a2 interface{}) *mockOrderbookDistributed_Cancel_Call {
	return &mockOrderbookDistributed_Cancel_Call{Call: _e.mock.On("Cancel", _a0, _a1, _a2)}
}

func (_c *mockOrderbookDistributed_Cancel_Call) Run(run func(_a0 context.Context, _a1 float64, _a2 *Order)) *mockOrderbookDistributed_Cancel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(float64), args[2].(*Order))
	})
	return _c
}

func (_c *mockOrderbookDistributed_Cancel_Call) Return(_a0 error) *mockOrderbookDistributed_Cancel_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockOrderbookDistributed_Cancel_Call) RunAndReturn(run func(context.Context, float64, *Order) error) *mockOrderbookDistributed_Cancel_Call {
	_c.Call.Return(run)
	return _c
}

// GetAskLimit provides a mock function with given fields: _a0
func (_m *mockOrderbookDistributed) GetAskLimit(_a0 float64) *LimitOrder {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetAskLimit")
	}

	var r0 *LimitOrder
	if rf, ok := ret.Get(0).(func(float64) *LimitOrder); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*LimitOrder)
		}
	}

	return r0
}

// mockOrderbookDistributed_GetAskLimit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAskLimit'
type mockOrderbookDistributed_GetAskLimit_Call struct {
	*mock.Call
}

// GetAskLimit is a helper method to define mock.On call
//   - _a0 float64
func (_e *mockOrderbookDistributed_Expecter) GetAskLimit(_a0 interface{}) *mockOrderbookDistributed_GetAskLimit_Call {
	return &mockOrderbookDistributed_GetAskLimit_Call{Call: _e.mock.On("GetAskLimit", _a0)}
}

func (_c *mockOrderbookDistributed_GetAskLimit_Call) Run(run func(_a0 float64)) *mockOrderbookDistributed_GetAskLimit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(float64))
	})
	return _c
}

func (_c *mockOrderbookDistributed_GetAskLimit_Call) Return(_a0 *LimitOrder) *mockOrderbookDistributed_GetAskLimit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockOrderbookDistributed_GetAskLimit_Call) RunAndReturn(run func(float64) *LimitOrder) *mockOrderbookDistributed_GetAskLimit_Call {
	_c.Call.Return(run)
	return _c
}

// GetBestBid provides a mock function with given fields: _a0
func (_m *mockOrderbookDistributed) GetBestBid(_a0 context.Context) float64 {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetBestBid")
	}

	var r0 float64
	if rf, ok := ret.Get(0).(func(context.Context) float64); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(float64)
	}

	return r0
}

// mockOrderbookDistributed_GetBestBid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBestBid'
type mockOrderbookDistributed_GetBestBid_Call struct {
	*mock.Call
}

// GetBestBid is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *mockOrderbookDistributed_Expecter) GetBestBid(_a0 interface{}) *mockOrderbookDistributed_GetBestBid_Call {
	return &mockOrderbookDistributed_GetBestBid_Call{Call: _e.mock.On("GetBestBid", _a0)}
}

func (_c *mockOrderbookDistributed_GetBestBid_Call) Run(run func(_a0 context.Context)) *mockOrderbookDistributed_GetBestBid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockOrderbookDistributed_GetBestBid_Call) Return(_a0 float64) *mockOrderbookDistributed_GetBestBid_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockOrderbookDistributed_GetBestBid_Call) RunAndReturn(run func(context.Context) float64) *mockOrderbookDistributed_GetBestBid_Call {
	_c.Call.Return(run)
	return _c
}

// GetBestOffer provides a mock function with given fields: _a0
func (_m *mockOrderbookDistributed) GetBestOffer(_a0 context.Context) float64 {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetBestOffer")
	}

	var r0 float64
	if rf, ok := ret.Get(0).(func(context.Context) float64); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(float64)
	}

	return r0
}

// mockOrderbookDistributed_GetBestOffer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBestOffer'
type mockOrderbookDistributed_GetBestOffer_Call struct {
	*mock.Call
}

// GetBestOffer is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *mockOrderbookDistributed_Expecter) GetBestOffer(_a0 interface{}) *mockOrderbookDistributed_GetBestOffer_Call {
	return &mockOrderbookDistributed_GetBestOffer_Call{Call: _e.mock.On("GetBestOffer", _a0)}
}

func (_c *mockOrderbookDistributed_GetBestOffer_Call) Run(run func(_a0 context.Context)) *mockOrderbookDistributed_GetBestOffer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockOrderbookDistributed_GetBestOffer_Call) Return(_a0 float64) *mockOrderbookDistributed_GetBestOffer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockOrderbookDistributed_GetBestOffer_Call) RunAndReturn(run func(context.Context) float64) *mockOrderbookDistributed_GetBestOffer_Call {
	_c.Call.Return(run)
	return _c
}

// GetBidLimit provides a mock function with given fields: _a0
func (_m *mockOrderbookDistributed) GetBidLimit(_a0 float64) *LimitOrder {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetBidLimit")
	}

	var r0 *LimitOrder
	if rf, ok := ret.Get(0).(func(float64) *LimitOrder); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*LimitOrder)
		}
	}

	return r0
}

// mockOrderbookDistributed_GetBidLimit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBidLimit'
type mockOrderbookDistributed_GetBidLimit_Call struct {
	*mock.Call
}

// GetBidLimit is a helper method to define mock.On call
//   - _a0 float64
func (_e *mockOrderbookDistributed_Expecter) GetBidLimit(_a0 interface{}) *mockOrderbookDistributed_GetBidLimit_Call {
	return &mockOrderbookDistributed_GetBidLimit_Call{Call: _e.mock.On("GetBidLimit", _a0)}
}

func (_c *mockOrderbookDistributed_GetBidLimit_Call) Run(run func(_a0 float64)) *mockOrderbookDistributed_GetBidLimit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(float64))
	})
	return _c
}

func (_c *mockOrderbookDistributed_GetBidLimit_Call) Return(_a0 *LimitOrder) *mockOrderbookDistributed_GetBidLimit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockOrderbookDistributed_GetBidLimit_Call) RunAndReturn(run func(float64) *LimitOrder) *mockOrderbookDistributed_GetBidLimit_Call {
	_c.Call.Return(run)
	return _c
}

// Lock provides a mock function with given fields: _a0
func (_m *mockOrderbookDistributed) Lock(_a0 context.Context) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Lock")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockOrderbookDistributed_Lock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Lock'
type mockOrderbookDistributed_Lock_Call struct {
	*mock.Call
}

// Lock is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *mockOrderbookDistributed_Expecter) Lock(_a0 interface{}) *mockOrderbookDistributed_Lock_Call {
	return &mockOrderbookDistributed_Lock_Call{Call: _e.mock.On("Lock", _a0)}
}

func (_c *mockOrderbookDistributed_Lock_Call) Run(run func(_a0 context.Context)) *mockOrderbookDistributed_Lock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockOrderbookDistributed_Lock_Call) Return(_a0 error) *mockOrderbookDistributed_Lock_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockOrderbookDistributed_Lock_Call) RunAndReturn(run func(context.Context) error) *mockOrderbookDistributed_Lock_Call {
	_c.Call.Return(run)
	return _c
}

// Unlock provides a mock function with given fields: _a0
func (_m *mockOrderbookDistributed) Unlock(_a0 context.Context) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Unlock")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockOrderbookDistributed_Unlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unlock'
type mockOrderbookDistributed_Unlock_Call struct {
	*mock.Call
}

// Unlock is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *mockOrderbookDistributed_Expecter) Unlock(_a0 interface{}) *mockOrderbookDistributed_Unlock_Call {
	return &mockOrderbookDistributed_Unlock_Call{Call: _e.mock.On("Unlock", _a0)}
}

func (_c *mockOrderbookDistributed_Unlock_Call) Run(run func(_a0 context.Context)) *mockOrderbookDistributed_Unlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockOrderbookDistributed_Unlock_Call) Return(_a0 error) *mockOrderbookDistributed_Unlock_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockOrderbookDistributed_Unlock_Call) RunAndReturn(run func(context.Context) error) *mockOrderbookDistributed_Unlock_Call {
	_c.Call.Return(run)
	return _c
}

// newMockOrderbookDistributed creates a new instance of mockOrderbookDistributed. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockOrderbookDistributed(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockOrderbookDistributed {
	mock := &mockOrderbookDistributed{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
