// Code generated by mockery v2.44.1. DO NOT EDIT.

package hftorderbook

import (
	context "context"

	redis "github.com/go-redis/redis/v8"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// mockRedisPipeliner is an autogenerated mock type for the redisPipeliner type
type mockRedisPipeliner struct {
	mock.Mock
}

type mockRedisPipeliner_Expecter struct {
	mock *mock.Mock
}

func (_m *mockRedisPipeliner) EXPECT() *mockRedisPipeliner_Expecter {
	return &mockRedisPipeliner_Expecter{mock: &_m.Mock}
}

// Del provides a mock function with given fields: ctx, keys
func (_m *mockRedisPipeliner) Del(ctx context.Context, keys ...string) *redis.IntCmd {
	_va := make([]interface{}, len(keys))
	for _i := range keys {
		_va[_i] = keys[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Del")
	}

	var r0 *redis.IntCmd
	if rf, ok := ret.Get(0).(func(context.Context, ...string) *redis.IntCmd); ok {
		r0 = rf(ctx, keys...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*redis.IntCmd)
		}
	}

	return r0
}

// mockRedisPipeliner_Del_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Del'
type mockRedisPipeliner_Del_Call struct {
	*mock.Call
}

// Del is a helper method to define mock.On call
//   - ctx context.Context
//   - keys ...string
func (_e *mockRedisPipeliner_Expecter) Del(ctx interface{}, keys ...interface{}) *mockRedisPipeliner_Del_Call {
	return &mockRedisPipeliner_Del_Call{Call: _e.mock.On("Del",
		append([]interface{}{ctx}, keys...)...)}
}

func (_c *mockRedisPipeliner_Del_Call) Run(run func(ctx context.Context, keys ...string)) *mockRedisPipeliner_Del_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *mockRedisPipeliner_Del_Call) Return(_a0 *redis.IntCmd) *mockRedisPipeliner_Del_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockRedisPipeliner_Del_Call) RunAndReturn(run func(context.Context, ...string) *redis.IntCmd) *mockRedisPipeliner_Del_Call {
	_c.Call.Return(run)
	return _c
}

// Exec provides a mock function with given fields: ctx
func (_m *mockRedisPipeliner) Exec(ctx context.Context) ([]redis.Cmder, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 []redis.Cmder
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]redis.Cmder, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []redis.Cmder); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]redis.Cmder)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockRedisPipeliner_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type mockRedisPipeliner_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockRedisPipeliner_Expecter) Exec(ctx interface{}) *mockRedisPipeliner_Exec_Call {
	return &mockRedisPipeliner_Exec_Call{Call: _e.mock.On("Exec", ctx)}
}

func (_c *mockRedisPipeliner_Exec_Call) Run(run func(ctx context.Context)) *mockRedisPipeliner_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockRedisPipeliner_Exec_Call) Return(_a0 []redis.Cmder, _a1 error) *mockRedisPipeliner_Exec_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockRedisPipeliner_Exec_Call) RunAndReturn(run func(context.Context) ([]redis.Cmder, error)) *mockRedisPipeliner_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: ctx, key, value, expiration
func (_m *mockRedisPipeliner) Set(ctx context.Context, key string, value interface{}, expiration time.Duration) *redis.StatusCmd {
	ret := _m.Called(ctx, key, value, expiration)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 *redis.StatusCmd
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}, time.Duration) *redis.StatusCmd); ok {
		r0 = rf(ctx, key, value, expiration)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*redis.StatusCmd)
		}
	}

	return r0
}

// mockRedisPipeliner_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type mockRedisPipeliner_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value interface{}
//   - expiration time.Duration
func (_e *mockRedisPipeliner_Expecter) Set(ctx interface{}, key interface{}, value interface{}, expiration interface{}) *mockRedisPipeliner_Set_Call {
	return &mockRedisPipeliner_Set_Call{Call: _e.mock.On("Set", ctx, key, value, expiration)}
}

func (_c *mockRedisPipeliner_Set_Call) Run(run func(ctx context.Context, key string, value interface{}, expiration time.Duration)) *mockRedisPipeliner_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(interface{}), args[3].(time.Duration))
	})
	return _c
}

func (_c *mockRedisPipeliner_Set_Call) Return(_a0 *redis.StatusCmd) *mockRedisPipeliner_Set_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockRedisPipeliner_Set_Call) RunAndReturn(run func(context.Context, string, interface{}, time.Duration) *redis.StatusCmd) *mockRedisPipeliner_Set_Call {
	_c.Call.Return(run)
	return _c
}

// newMockRedisPipeliner creates a new instance of mockRedisPipeliner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockRedisPipeliner(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockRedisPipeliner {
	mock := &mockRedisPipeliner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
