// Code generated by mockery v2.44.1. DO NOT EDIT.

package hftorderbook

import (
	context "context"

	redis "github.com/go-redis/redis/v8"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// mockRedisClient is an autogenerated mock type for the redisClient type
type mockRedisClient struct {
	mock.Mock
}

type mockRedisClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockRedisClient) EXPECT() *mockRedisClient_Expecter {
	return &mockRedisClient_Expecter{mock: &_m.Mock}
}

// Del provides a mock function with given fields: ctx, keys
func (_m *mockRedisClient) Del(ctx context.Context, keys ...string) *redis.IntCmd {
	_va := make([]interface{}, len(keys))
	for _i := range keys {
		_va[_i] = keys[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Del")
	}

	var r0 *redis.IntCmd
	if rf, ok := ret.Get(0).(func(context.Context, ...string) *redis.IntCmd); ok {
		r0 = rf(ctx, keys...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*redis.IntCmd)
		}
	}

	return r0
}

// mockRedisClient_Del_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Del'
type mockRedisClient_Del_Call struct {
	*mock.Call
}

// Del is a helper method to define mock.On call
//   - ctx context.Context
//   - keys ...string
func (_e *mockRedisClient_Expecter) Del(ctx interface{}, keys ...interface{}) *mockRedisClient_Del_Call {
	return &mockRedisClient_Del_Call{Call: _e.mock.On("Del",
		append([]interface{}{ctx}, keys...)...)}
}

func (_c *mockRedisClient_Del_Call) Run(run func(ctx context.Context, keys ...string)) *mockRedisClient_Del_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *mockRedisClient_Del_Call) Return(_a0 *redis.IntCmd) *mockRedisClient_Del_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockRedisClient_Del_Call) RunAndReturn(run func(context.Context, ...string) *redis.IntCmd) *mockRedisClient_Del_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, key
func (_m *mockRedisClient) Get(ctx context.Context, key string) *redis.StringCmd {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *redis.StringCmd
	if rf, ok := ret.Get(0).(func(context.Context, string) *redis.StringCmd); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*redis.StringCmd)
		}
	}

	return r0
}

// mockRedisClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type mockRedisClient_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *mockRedisClient_Expecter) Get(ctx interface{}, key interface{}) *mockRedisClient_Get_Call {
	return &mockRedisClient_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *mockRedisClient_Get_Call) Run(run func(ctx context.Context, key string)) *mockRedisClient_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *mockRedisClient_Get_Call) Return(_a0 *redis.StringCmd) *mockRedisClient_Get_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockRedisClient_Get_Call) RunAndReturn(run func(context.Context, string) *redis.StringCmd) *mockRedisClient_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Keys provides a mock function with given fields: ctx, pattern
func (_m *mockRedisClient) Keys(ctx context.Context, pattern string) *redis.StringSliceCmd {
	ret := _m.Called(ctx, pattern)

	if len(ret) == 0 {
		panic("no return value specified for Keys")
	}

	var r0 *redis.StringSliceCmd
	if rf, ok := ret.Get(0).(func(context.Context, string) *redis.StringSliceCmd); ok {
		r0 = rf(ctx, pattern)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*redis.StringSliceCmd)
		}
	}

	return r0
}

// mockRedisClient_Keys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Keys'
type mockRedisClient_Keys_Call struct {
	*mock.Call
}

// Keys is a helper method to define mock.On call
//   - ctx context.Context
//   - pattern string
func (_e *mockRedisClient_Expecter) Keys(ctx interface{}, pattern interface{}) *mockRedisClient_Keys_Call {
	return &mockRedisClient_Keys_Call{Call: _e.mock.On("Keys", ctx, pattern)}
}

func (_c *mockRedisClient_Keys_Call) Run(run func(ctx context.Context, pattern string)) *mockRedisClient_Keys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *mockRedisClient_Keys_Call) Return(_a0 *redis.StringSliceCmd) *mockRedisClient_Keys_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockRedisClient_Keys_Call) RunAndReturn(run func(context.Context, string) *redis.StringSliceCmd) *mockRedisClient_Keys_Call {
	_c.Call.Return(run)
	return _c
}

// Pipeline provides a mock function with given fields:
func (_m *mockRedisClient) Pipeline() redisPipeliner {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Pipeline")
	}

	var r0 redisPipeliner
	if rf, ok := ret.Get(0).(func() redisPipeliner); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(redisPipeliner)
		}
	}

	return r0
}

// mockRedisClient_Pipeline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pipeline'
type mockRedisClient_Pipeline_Call struct {
	*mock.Call
}

// Pipeline is a helper method to define mock.On call
func (_e *mockRedisClient_Expecter) Pipeline() *mockRedisClient_Pipeline_Call {
	return &mockRedisClient_Pipeline_Call{Call: _e.mock.On("Pipeline")}
}

func (_c *mockRedisClient_Pipeline_Call) Run(run func()) *mockRedisClient_Pipeline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockRedisClient_Pipeline_Call) Return(_a0 redisPipeliner) *mockRedisClient_Pipeline_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockRedisClient_Pipeline_Call) RunAndReturn(run func() redisPipeliner) *mockRedisClient_Pipeline_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: ctx, key, value, expiration
func (_m *mockRedisClient) Set(ctx context.Context, key string, value interface{}, expiration time.Duration) *redis.StatusCmd {
	ret := _m.Called(ctx, key, value, expiration)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 *redis.StatusCmd
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}, time.Duration) *redis.StatusCmd); ok {
		r0 = rf(ctx, key, value, expiration)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*redis.StatusCmd)
		}
	}

	return r0
}

// mockRedisClient_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type mockRedisClient_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value interface{}
//   - expiration time.Duration
func (_e *mockRedisClient_Expecter) Set(ctx interface{}, key interface{}, value interface{}, expiration interface{}) *mockRedisClient_Set_Call {
	return &mockRedisClient_Set_Call{Call: _e.mock.On("Set", ctx, key, value, expiration)}
}

func (_c *mockRedisClient_Set_Call) Run(run func(ctx context.Context, key string, value interface{}, expiration time.Duration)) *mockRedisClient_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(interface{}), args[3].(time.Duration))
	})
	return _c
}

func (_c *mockRedisClient_Set_Call) Return(_a0 *redis.StatusCmd) *mockRedisClient_Set_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockRedisClient_Set_Call) RunAndReturn(run func(context.Context, string, interface{}, time.Duration) *redis.StatusCmd) *mockRedisClient_Set_Call {
	_c.Call.Return(run)
	return _c
}

// SetNX provides a mock function with given fields: ctx, key, value, expiration
func (_m *mockRedisClient) SetNX(ctx context.Context, key string, value interface{}, expiration time.Duration) *redis.BoolCmd {
	ret := _m.Called(ctx, key, value, expiration)

	if len(ret) == 0 {
		panic("no return value specified for SetNX")
	}

	var r0 *redis.BoolCmd
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}, time.Duration) *redis.BoolCmd); ok {
		r0 = rf(ctx, key, value, expiration)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*redis.BoolCmd)
		}
	}

	return r0
}

// mockRedisClient_SetNX_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetNX'
type mockRedisClient_SetNX_Call struct {
	*mock.Call
}

// SetNX is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value interface{}
//   - expiration time.Duration
func (_e *mockRedisClient_Expecter) SetNX(ctx interface{}, key interface{}, value interface{}, expiration interface{}) *mockRedisClient_SetNX_Call {
	return &mockRedisClient_SetNX_Call{Call: _e.mock.On("SetNX", ctx, key, value, expiration)}
}

func (_c *mockRedisClient_SetNX_Call) Run(run func(ctx context.Context, key string, value interface{}, expiration time.Duration)) *mockRedisClient_SetNX_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(interface{}), args[3].(time.Duration))
	})
	return _c
}

func (_c *mockRedisClient_SetNX_Call) Return(_a0 *redis.BoolCmd) *mockRedisClient_SetNX_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockRedisClient_SetNX_Call) RunAndReturn(run func(context.Context, string, interface{}, time.Duration) *redis.BoolCmd) *mockRedisClient_SetNX_Call {
	_c.Call.Return(run)
	return _c
}

// newMockRedisClient creates a new instance of mockRedisClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockRedisClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockRedisClient {
	mock := &mockRedisClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
